<?php

/**
* Model:    <modelname>
*
* (!)       Model generated by the create Script.
*/
 
class <modelname> extends MyModel
{
    //--
    //-- Model Actions
    //-- 

    var $model_actions = array(
            
            // Example task
            'hello_world' => array(
                'name'          => 'Hello World',
                'description'   => 'This method returns a hello world.',
                ),
    );
    
    //--
    //-- Model Actions (implementation)
    //--
    
    /**
    * This model returns a hello world
    * @return  mixed   string
    */
    public final function hello_world()
    {
        return("Hello world!");
    }
}
?>
