###
# Enabled langs config file
#
# This file informs the application which languages
# are available, so no unknown langfiles are loaded
# and cache files are generated for each one of them.
#
# Example:
#
# en: English
# es: Spanish
# it: Italian
# fr: French
# ge: German
##
