###
# Routes Config File
#
# Regular expressions can be used to redirect a request (fake or not)
# to another request. This is specially useful to create nice 
# looking urls, shut down the whole site for manteinance or 
# prevent losing user's bookmarks.
#
# A regular expression is used to match the original url. Then,
# a new request is written. One or more of the following
# tokens can be used.
#
# Valid tokens:
#
#    :controler -> requested controller
#    :action    -> requested action
#    :p1        -> requested parameter 1
#    :pn        -> requested parameter n
#    :p10       -> requested parameter 10
#
# Each rule is written like this:
#
# [PCRE Regular expression]: [Redirection]
##

###
# Shortcut for the built-in static pages controller
#
# Request: 		pages / {page}
# Redirect: 	pages / view / {page}
# Example:		pages/foo -> pages/view/foo
##
# /^(pages)\/[^\/]+$/i: "pages/view/:action"

###
# Shuts down all website controllers, making the whole website unavailable.
#
# Request: All requests
# Redirect: Down for maintenance page
##
# /^.*$/: "pages/view/down-for-maintenance"

###
# Hide the admin site using other controller url for all requests.
# If enabled, change the menu links in app/config/siteadmin.yml
#
# Request:      myadminsite/:action/:p1/:p2/:p3
# Redirect:     admin/:action/:p1/:p2/:p3
##
# /^myadminsite$/i: "admin/login"
# /^myadminsite\/[^\/]+/i: "admin/:action"
# /^myadminsite\/[^\/]+\/[^\/]+/i: "admin/:action/:p1"
# /^myadminsite\/[^\/]+\/[^\/]+\/[^\/]+/i: "admin/:action/:p1/:p2"
# /^myadminsite\/[^\/]+\/[^\/]+\/[^\/]+\/[^\/]+/i: "admin/:action/:p1/:p2/:p3"

###
# Disable original admin site urls.
# Don't enable without creating an entry point above.
#
# Request: admin/:action/:p1:/:p2
# Redirect: index/index
##
# /^admin\/[^\/]+/i: "index/index"
# /^admin\/[^\/]+\/[^\/]+/i: "index/index"
# /^admin\/[^\/]+\/[^\/]+\/[^\/]+/i: "index/index"