<?php

/**
 * Controller: 	Pages
 * (!)          Controller generated by the create script
 * @            Serves static pages at app/pages
 */

class PagesWebController extends MyWebController
{
    //--
    //-- Controller Options
    //-- 
    
    //var $ignore_messages = true;			// Ignore validation and flash messages 
    //var $layout = 'another_layout_name';	// Set another layout for this controller
    //var $sessionAllowed = 'Session_name';	// Redirect 403 Forbidden unless this session is created
    //var $load = array();                  // Array of libraries to autoload for this controller
    
    //--
    //-- Titles, descriptions and keywords for each page
    //-- Add and edit your pages below
    //--
    var $page_data = array(

            // Terms and conditions
            'terms-and-conditions'  => array(
                'title'       => 'Terms and Conditions',
                'description' => 'Terms and conditions of use of the website',
                'keywords'    => 'terms, conditions',
            ),
            
            // Privacy Policy
            'privacy-policy'  => array(
                'title'       => 'Privacy Policy',
                'description' => 'Privacy policy of the website',
                'keywords'    => 'privacy, policy',
            ),
            
            // Down for maintenance
            'down-for-maintenance'  => array(
                'title'       => 'Down for maintenance',
                'description' => 'The website is temporarily down for maintenance.',
                'keywords'    => 'down, maintenance, temporarily',
            ),
            
    );
    
    //--------------------------------------------------------
    
    /**
    * Default controller function. Start here!
    */
   
    public function view(string $page)
    {
        // Title
        $this->setTitle(TITLE);

        // Description and keywords
        if(isset($this->page_data[$page]['title'])) $this->appendTitle($this->page_data[$page]['title']);
        if(isset($this->page_data[$page]['description'])) $this->set('meta_description', $this->page_data[$page]['description']);
        if(isset($this->page_data[$page]['keywords'])) $this->set('meta_keywords', $this->page_data[$page]['keywords']);


        // Page file
        $page_file = USERPAGES . $page .".php";
        
        // Does it exist?
        if(file_exists($page_file))
        {
            $this->set('include_page', $page_file);
        
        // 404 or error in testing
        } else {
            $this->core->abort("The page ". $page_file ." does not exist", "Page not found");
        }
         
    }
}

?>
